a=int(input("Enter the first number: "))
b=int(input("Enter the second number: "))
print("The sum is",a+b)
print("The difference is",a-b)
print("The product is",a*b)
print("The division is",a/b)
print("The division output in integer form is",a//b)
print("The remainder is",a%b)
print("The exponential is",a**b)